version: 1.2
workflows:
  - name: annotate_variants
    subclass: WDL
    primaryDescriptorPath: /wdl/workflow.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: denovo_svs
    subclass: WDL
    primaryDescriptorPath: /wdl/denovo_svs.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: compare_svs
    subclass: WDL
    primaryDescriptorPath: /wdl/compare_svs.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
